### ISSUE TITLE
要不要改成直接跳转？

### ISSUE THREAD

**Issue by OlingCat** [plfa-zh/plfa-zh.github.io#1]
要不要加段
```html
<script language="javascript" type="text/javascript"> 
window.location.href='https://agda-zh.github.io/PLFA-zh/';
</script>
```
改成直接跳转？

**Comment by sgalal** [comment]
Why is @plfa-zh a user instead of an organization? 😂

**Comment by OlingCat** [comment]
> Why is @plfa-zh a user instead of an organization?

这就是问题= =
也许可以删掉重建为 orgs？然后把 https://agda-zh.github.io/PLFA-zh/ 的 Travis CI 部署放到这里，毕竟这里的 URL 更简单好记些。

**Comment by sgalal** [comment]
也许可以删掉重建为 orgs？然后把 https://agda-zh.github.io/PLFA-zh/ 的 Travis CI 部署放到这里，毕竟这里的 URL 更简单好记些。

支持

**Comment by roger-uw** [comment]
> > Why is @plfa-zh a user instead of an organization?
> 
> 这就是问题= =
> 也许可以删掉重建为 orgs？然后把 https://agda-zh.github.io/PLFA-zh/ 的 Travis CI 部署放到这里，毕竟这里的 URL 更简单好记些。

已经改为 organization 账号；已经同时部署到 https://agda-zh.github.io/PLFA-zh/ 和 https://plfa-zh.github.io/
